### ISSUE TITLE
MQTT Driven Tiles

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#114]
### Discussed in https://github.com/Daveiano/weewx-wdc/discussions/96

<div type='discussions-op-text'>

<sup>Originally posted by **gary-hammer** November  5, 2022</sup>
Any chance of using MQTT data to update tiles?</div>

**TODO**

- [x] Support classic layout
- [x] Respect show min/max time
- [x] Respect loop vs archive for totals (aggregation)
- [x] Add Tests
- [x] Document

**Research**

_MQTT Broker_
- ~~https://us-east-1.console.aws.amazon.com/amazon-mq/home~~
- https://github.com/weewx/weewx/wiki/mqtt
- https://github.com/matthewwall/weewx-mqtt
- https://hub.docker.com/_/eclipse-mosquitto
- https://aws.amazon.com/blogs/iot/how-to-bridge-mosquitto-mqtt-broker-to-aws-iot/
- https://www.woellsdorf-wetter.de/software/mosquitto.html

__Testing__
- https://playwright.dev/docs/network#websockets
- https://github.com/microsoft/playwright/issues/4488
