### ISSUE TITLE
Add slot for webcam image/add optional extra webcam page

### ISSUE THREAD

**Issue by Daveiano** [Daveiano/weewx-wdc#127]
## Motivation

> One thing noted by one of my users is the webcam image that I had on my previous site. I have taken a look through but cannot see anything about adding either an image or a live feed to the main page.

## Tasks

- [x] Add additional optional "Web Cam/Externals" Page which works like the current about page, the user needs to enable and edit the page
- [x]  Some basic Code Snippets in the wiki for users to easily create 2-Column layouts, 3-Column layouts, Headings or whatever
- [x] Tabs on Front Page to switch between Radar and cams
- [x] Document
- [x] Test
